export default {
  TITLE: 'title',
  DATE_OF_CREATION: 'dateOfCreation',
  VALUE: 'value',
  TYPE: 'type',
  DATE_OF_INCLUSION: 'dateOfInclusion',
  RELATIVE_MONTH: 'relativeMonth',
  DESCRIPTION: 'description',
  FORMATION: 'formation',
  DATE: 'date',
  MUSICIANS: 'musicians',
  MUSICIANSSTATUS: 'musiciansstatus',
  STATUS: 'status',
  dateOfCreation: 'dateOfCreation',
};
